### ISSUE TITLE
[PE-D][Tester D] Expected output differs from actual output for list-intake

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-2/tp#262]
![Screenshot 2024-11-08 162328.png](https://raw.githubusercontent.com/parasytezz/ped/main/files/a9008111-7420-4815-96ed-45b143d55d8a.png)

![Screenshot 2024-11-08 162334.png](https://raw.githubusercontent.com/parasytezz/ped/main/files/55e63e0f-4261-493d-9c40-568075c3c59d.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: parasytezz/ped#4

**Comment by ayushi0803** [comment]
done 
please close @Zackermax
