### ISSUE TITLE
[PE-D][Tester D] Expected output differs from actual output for list-water

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2113-W13-2/tp#267]
![Screenshot 2024-11-08 162152.png](https://raw.githubusercontent.com/parasytezz/ped/main/files/f670839d-3c2c-4def-b93d-ceaeca7109f4.png)

![Screenshot 2024-11-08 164015.png](https://raw.githubusercontent.com/parasytezz/ped/main/files/7b03889a-7c00-4e6a-9b32-cc9428cf845c.png)

-------------
Labels: `severity.VeryLow` `type.DocumentationBug`
original: parasytezz/ped#7

**Comment by ayushi0803** [comment]
done 
@Zackermax
