### ISSUE TITLE
[PE-D][Tester E]  gperformance and gpoints command not listed in help command output

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-2/tp#284]
![image.png](https://raw.githubusercontent.com/ryryry-3302/ped/main/files/6ab870a3-3d08-446b-a205-89badb050181.png)
- User is only able to know about the existence of these features by reading the UG, I believe it would be good to add it to your help command

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: ryryry-3302/ped#11

**Comment by TheDinos** [comment]
Same issue as #304, closing issue as it is being fixed in that issue.
