### ISSUE TITLE
[PE-D][Tester C] Goal function accepts date input before system date

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2113-W13-2/tp#300]
![image.png](https://raw.githubusercontent.com/ctzeyong/ped/main/files/cef5ae61-8e2a-4974-ab33-b76cea827eed.png)

Since it is a goal function, it should be set for the future, not the past. Not a huge issue but would be great to reject such input.

-------------
Labels: `type.FeatureFlaw` `severity.Low`
original: ctzeyong/ped#15

**Comment by ayushi0803** [comment]
to be closed @Zackermax
